# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20160217_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
